template:
  path: s3-bucket.yaml
stack_name: bridge-downstream-intermediate-bucket
parameters:
  BucketName: bridge-downstream-intermediate-data
stack_tags:
  {{ stack_group_config.default_stack_tags }}
