template:
  type: sam
  path: src/lambda/template.yaml
  artifact_bucket_name: {{ stack_group_config.artifact_bucket_name }}
  artifact_prefix: 'BridgeDownstream/{{ stack_group_config.namespace }}/lambda/'
stack_name: '{{ stack_group_config.namespace }}-lambda-SQSToGlue'
dependencies:
  - develop/namespaced/sqs-queue.yaml
stack_tags: {{ stack_group_config.default_stack_tags }}
parameters:
  Namespace: {{ stack_group_config.namespace }}
  SQSQueueArn: !stack_output_external '{{ stack_group_config.namespace }}-sqs-SNSToLambda::PrimaryQueueArn'
