project_code: bridge_downstream
namespace: {{ var.namespace | default('bridge-downstream') }}
latest_version: v0.1
region: us-east-1
synapseAuthSsmParameterName: synapse-bridgedownstream-auth
synapseBridgeDownstreamUserId: 3432808
admincentral_cf_bucket: bootstrap-awss3cloudformationbucket-19qromfd235z9
default_stack_tags:
  Department: IBC
  Project: mobile-toolbox
  OwnerEmail: aws-mobilehealth-dataengineering-dev@sagebase.org
j2_environment:
  extensions:
    - jinja2.ext.do
    - jinja2.ext.debug
