project_code: bridge_downstream
region: us-east-1
artifact_bucket_name: sceptre-cloudformation-bucket-bucket-65ci2qog5w6l
default_stack_tags:
  Department: IBC
  Project: mobile-toolbox
  OwnerEmail: aws-mobilehealth-dataengineering-dev@sagebase.org
