template_path: glue-spark-job.j2
stack_name: glue-job-S3ToJsonS3
#{% set BranchOrTagName='main' %}
parameters:
  JobRole: !stack_output_external glue-job-role::RoleArn
  S3BucketName: !stack_output_external bridge-downstream-dev-intermediate-bucket::BucketName
  BookmarkOption: job-bookmark-disable
  JobDescription: Convert data to JSONS3 data
  MaxConcurrentRuns: 150
  S3ScriptLocation: s3://{{ stack_group_config.artifact_bucket_name }}/BridgeDownstream/{{ BranchOrTagName }}/glue/jobs/s3_to_json_s3.py
  UniqueId: !rcmd git rev-parse HEAD
  SynapseAuthSsmParameterName: {{ stack_group_config.synapseAuthSsmParameterName }}
  AdditionalPythonModules: 'synapseclient'
stack_tags:
  {{ stack_group_config.default_stack_tags }}
