template_path: glue-triggers.yaml
stack_name: glue-triggers
dependencies:
  - develop/glue-jobs.yaml
  - develop/glue-workflows.yaml
parameters:
  S3ToJsonWorkflowName: !stack_output_external glue-workflows::S3ToJsonWorkflowName
  S3ToJsonS3JobName: !stack_output_external glue-jobs::S3ToJsonS3JobName
  JsonToParquetWorkflowName: !stack_output_external glue-workflows::JsonToParquetWorkflowName
  AnswersParquetJobName: !stack_output_external glue-jobs::AnswersParquetJobName
  InfoParquetJobName: !stack_output_external glue-jobs::InfoParquetJobName
  MetadataParquetJobName: !stack_output_external glue-jobs::MetadataParquetJobName
  MicrophoneLevelsParquetJobName: !stack_output_external glue-jobs::MicrophoneLevelsParquetJobName
  MotionParquetJobName: !stack_output_external glue-jobs::MotionParquetJobName
  TaskDataParquetJobName: !stack_output_external glue-jobs::TaskDataParquetJobName
  TaskResultParquetJobName: !stack_output_external glue-jobs::TaskResultParquetJobName
  WeatherParquetJobName: !stack_output_external glue-jobs::WeatherParquetJobName
