template:
  path: glue-job-role.yaml
stack_name: glue-job-role
dependencies:
  - develop/namespaced/invalid-sqs-queue.yaml
parameters:
  SsmParameterName: {{ stack_group_config.synapseAuthSsmParameterName }}
  InvalidSQSQueueArn: !stack_output_external '{{ stack_group_config.namespace }}-invalid-sqs::PrimaryQueueArn'
  S3IntermediateBucketName: !stack_output_external bridge-downstream-dev-intermediate-bucket::BucketName
  S3ParquetBucketName: !stack_output_external bridge-downstream-dev-parquet-bucket::BucketName
  S3ArtifactBucketName: {{ stack_group_config.artifact_bucket_name }}

stack_tags:
  {{ stack_group_config.default_stack_tags }}
