template_path: s3-bucket.yaml
stack_name: bridge-downstream-dev-intermediate-bucket
parameters:
  BucketName: bridge-downstream-dev-intermediate-data
stack_tags:
  {{ stack_group_config.default_stack_tags }}
