template_path: s3-bucket.yaml
stack_name: bridge-downstream-dev-input-bucket
parameters:
  BucketName: bridge-downstream-dev-input
  ReadOnlyAccessArns:
    - !stack_output_external glue-job-role::RoleArn
stack_tags:
  {{ stack_group_config.default_stack_tags }}
