template_path: s3-bucket.yaml
stack_name: bridge-downstream-dev-source-bucket
dependencies:
  - develop/glue-job-role.yaml
parameters:
  BucketName: bridge-downstream-dev-source
  ReadOnlyAccessArns:
    - !stack_output_external glue-job-role::RoleArn
  SynapseIds: '3432808'
stack_tags:
  {{ stack_group_config.default_stack_tags }}
stack_timeout: 10
hooks:
  after_launch:
    - !cmd "python src/scripts/setup_test_data/setup_test_data.py"
