template:
  type: s3
  path: '{{ stack_group_config.artifact_bucket_name }}/BridgeDownstream/{{ stack_group_config.namespace }}/templates/lambda/sns_to_glue/template.yaml'
stack_name: sqs-to-glue-lambda
stack_tags: {{ stack_group_config.default_stack_tags }}
parameters:
  Namespace: {{ stack_group_config.namespace }}
  SQSQueueArn: !stack_output_external '{{ stack_group_config.namespace }}-sqs-SNSToLambda::PrimaryQueueArn'
