template_path: study-pipeline-infra.yaml
stack_name: study-example-1
dependencies:
  - develop/glue-jobs.yaml
parameters:
  StudyName: example-study-1
  TemplateBucketName: {{ stack_group_config.artifact_bucket_name }}
  SourceBucketName: !stack_output_external bridge-downstream-dev-source-bucket::BucketName
  JsonBucketName: !stack_output_external bridge-downstream-dev-intermediate-bucket::BucketName
  ParquetBucketName: !stack_output_external bridge-downstream-dev-parquet-bucket::BucketName
  RoleArn: !stack_output_external glue-job-role::RoleArn
  ClassifierName: !stack_output_external array-of-records-classifier::ClassifierName
  SynapseAuthSsmParameterName: synapse-bridgedownstream-auth
  S3ToJsonS3JobName: !stack_output_external glue-jobs::S3ToJsonS3JobName
  AnswersParquetJobName: !stack_output_external glue-jobs::AnswersParquetJobName
  InfoParquetJobName: !stack_output_external glue-jobs::InfoParquetJobName
  MetadataParquetJobName: !stack_output_external glue-jobs::MetadataParquetJobName
  MicrophoneLevelsParquetJobName: !stack_output_external glue-jobs::MicrophoneLevelsParquetJobName
  MotionParquetJobName: !stack_output_external glue-jobs::MotionParquetJobName
  TaskDataParquetJobName: !stack_output_external glue-jobs::TaskDataParquetJobName
  TaskResultParquetJobName: !stack_output_external glue-jobs::TaskResultParquetJobName
  WeatherParquetJobName  : !stack_output_external glue-jobs::WeatherParquetJobName

stack_tags:
  {{ stack_group_config.default_stack_tags }}
