template_path: study-pipeline-infra.yaml
stack_name: study-example-1
parameters:
  StudyName: example-study-1
  TemplateBucketName: {{ stack_group_config.artifact_bucket_name }}
  SourceBucketName: !stack_output_external bridge-downstream-dev-source-bucket::BucketName
  JsonBucketName: !stack_output_external bridge-downstream-dev-intermediate-bucket::BucketName
  ParquetBucketName: !stack_output_external bridge-downstream-dev-parquet-bucket::BucketName
  RoleArn: !stack_output_external glue-job-role::RoleArn
  ClassifierName: !stack_output_external array-of-records-classifier::ClassifierName
  SynapseAuthSsmParameterName: synapse-bridgedownstream-auth
stack_tags:
  {{ stack_group_config.default_stack_tags }}
