AWSTemplateFormatVersion: '2010-09-09'
Description: TBD

Parameters:
  DatabaseName:
    Type: String

Resources:

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName
