AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Glue pythonshell job in the data catalog.

Parameters:

  JobDescription:
    Type: String
    Description: A fuller description of what the job does.
    Default: ''

  JobRole:
    Type: String
    Description: The name or ARN of the IAM role that will run this job.

  S3ScriptLocation:
    Type: String
    Description: The S3 path to the script that the job runs.

  PythonVersion:
    Type: String
    Description: Version of Python
    AllowedValues:
      - '2'
      - '3'
    Default: '3'

  MaxConcurrentRuns:
    Type: Number
    Description: >-
      Number of this type of glue job that can be run at same time (double).
    Default: 1 # Anticipate this will actually be something we want to require

  MaxRetries:
    Type: Number
    Description: How many times to retry the job if it fails (integer).
    Default: 0 # TODO change this to 1 after initial development

  TimeoutInMinutes:
    Type: Number
    Description: The job timeout in minutes (integer).
    Default: 120

  ContinuousLog:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']

  S3BucketName:
    Type: String
    Description: The name of the S3 bucket where temporary files are written.

  UniqueId:
    Type: String
    Description: A unique id for producing unique job names
    Default: ''

  SynapseAuthSsmParameterName:
    Type: String
    Description: >-
      The name of an ssm parameter whose value is Synapse service account
      personal access token


Resources:

  PythonShellJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: pythonshell
        ScriptLocation: !Ref S3ScriptLocation
        PythonVersion: !Ref PythonVersion
      DefaultArguments:
        --TempDir: !Sub s3://${S3BucketName}/tmp
        --enable-continuous-cloudwatch-log: !Ref ContinuousLog
        --enable-metrics: true
        --additional-python-modules: 'synapseclient'
        --ssm-parameter-name: !Ref SynapseAuthSsmParameterName
      Description: !Ref JobDescription
      ExecutionProperty:
        MaxConcurrentRuns: !Ref MaxConcurrentRuns
      MaxRetries: !Ref MaxRetries
      Name: !Sub '${AWS::StackName}-Job-${UniqueId}'
      Role: !Ref JobRole
      Timeout: !Ref TimeoutInMinutes

Outputs:

  JobName:
    Value: !Ref PythonShellJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-JobName'
