AWSTemplateFormatVersion: '2010-09-09'

Description: An IAM Role for the S3 to JSON Glue job

Parameters:

  SsmParameterName:
    Type: String
    Description: Name of the SSM parameter containing the Synapse auth token

  InvalidSQSQueueArn:
    Type: String
    Description: ARN of the SQS queue which we send invalid records to.

Resources:

  JobRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: GetSsmParam
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ssm:GetParameter
            Resource:
            - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SsmParameterName}
      - PolicyName: SendSQSMessage
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:SendMessage
            - sqs:GetQueueAttributes
            - sqs:GetQueueUrl
            Resource:
            - !Ref InvalidSQSQueueArn
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - glue.amazonaws.com
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'

Outputs:

  RoleName:
    Value: !Ref JobRole
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RoleName'

  RoleArn:
    Value: !GetAtt JobRole.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-RoleArn'
