AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  An AWS Glue job in the data catalog. An AWS Glue job encapsulates a script
  that connects to your source data, processes it, and then writes it out
  to your data target.

Parameters:

  JobName:
    Type: String
    Description: A short name to assign to this job definition.

  JobDescription:
    Type: String
    Description: A fuller description of what the job does.
    Default: ''

  JobRole:
    Type: String
    Description: The name or ARN of the IAM role that will run this job.

  JobLanguage:
    Type: String
    Description: The language used to write the job script.
    Default: python

  JobCommand:
    Type: String
    Default: glueetl
    AllowedValues:
      - glueetl
      - pythonshell

  GlueVersion:
    Type: String
    Description: >-
      AWS Glue version determines the versions of Apache Spark and Python
      that are available to the job.
    Default: '3.0' # Spark 3.1.1, Python 3.7

  S3ScriptLocation:
    Type: String
    Description: The S3 path to the script that the job runs.

  NumberOfWorkers:
    Type: Number
    Description: >-
      The number of workers of a defined workerType that are allocated
      when a job runs (integer).
    Default: 2

  MaxConcurrentRuns:
    Type: Number
    Description: >-
      Number of this type of glue job that can be run at same time (double).
    Default: 1 # Anticipate this will actually be something we want to require

  MaxRetries:
    Type: Number
    Description: How many times to retry the job if it fails (integer).
    Default: 0 # TODO change this to 1 after initial development

  TimeoutInMinutes:
    Type: Number
    Description: The job timeout in minutes (integer).
    Default: 120

  WorkerType:
    Type: String
    Description: >-
      The type of predefined worker that is allocated when a job runs.
      Must be one of Standard, G.1X, G.2X. For more information,
      see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html#cfn-glue-job-workertype.
    Default: Standard
    AllowedValues:
      - Standard
      - G.1X
      - G.2X

  # parameters for default arguments
  BookmarkOption:
    Type: String
    Description: Job bookmark behavior
    Default: job-bookmark-enable
    AllowedValues:
      - job-bookmark-enable
      - job-bookmark-disable
      - job-bookmark-pause

  ContinuousLog:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']

  GlueDatabaseName:
    Type: String
    Description: Name of the Glue database
    Default: ''

  S3OutputBucketName:
    Type: String
    Description: The name of the S3 bucket where temporary files are written.

  GlueTableName:
    Type: String
    Description: Name of the Glue table
    Default: ''

Resources:

  Job:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: !Ref JobCommand
        ScriptLocation: !Ref S3ScriptLocation
      DefaultArguments:
        --TempDir: !Sub s3://${S3OutputBucketName}/tmp
        --database: !Ref GlueDatabaseName
        --enable-continuous-cloudwatch-log: !Ref ContinuousLog
        --job-bookmark-option: !Ref BookmarkOption
        --job-language: !Ref JobLanguage
        --table: !Ref GlueTableName
      Description: !Ref JobDescription
      ExecutionProperty:
        MaxConcurrentRuns: !Ref MaxConcurrentRuns
      GlueVersion: !Ref GlueVersion
      MaxRetries: !Ref MaxRetries
      Name: !Ref JobName
      NumberOfWorkers: !Ref NumberOfWorkers
      Role: !Ref JobRole
      Timeout: !Ref TimeoutInMinutes
      WorkerType: !Ref WorkerType
