AWSTemplateFormatVersion: '2010-09-09'
Description: Groups metadata tables for Glue.

Parameters:
  DatabaseName:
    Type: String

Resources:

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName

Outputs:

  DatabaseName:
    Value: !Ref GlueDatabase
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-DatabaseName'
