AWSTemplateFormatVersion: '2010-09-09'

Description: The set of Glue jobs created for each study

Resources:
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Description: BridgeDownstream database

Outputs:

  DatabaseName:
    Value: !Ref GlueDatabase
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-DatabaseName'
