AWSTemplateFormatVersion: '2010-09-09'
Description: Glue Crawlers for mobile study Bridge files

Parameters:

  BucketName:
    Type: String
    Description: Name of the bucket to be crawled

  ClassifierName:
    Type: String
    Description: Name of the Glue classifier

  DatabaseName:
    Type: String
    Description: Name of the Glue database

  JsonPrefix:
    Type: String
    Description: Prefix of the S3 keys to be crawled
    Default: raw_json

  RoleArn:
    Type: String
    Description: The ARN of an IAM role that's used to access S3

  StudyName:
    Type: String
    Description: Study name, used to name crawlers or find correct data paths

Resources:

  StandardCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}},"Grouping":{"TableGroupingPolicy":"CombineCompatibleSchemas"}}'
      DatabaseName: !Ref DatabaseName
      Name: !Sub ${StudyName}-standard
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY
      Role: !Ref RoleArn
      SchemaChangePolicy:
        DeleteBehavior: LOG
        UpdateBehavior: LOG
      Targets:
        S3Targets:
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=answers/
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=info/
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=metadata/
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=taskData/
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=taskResult/
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=weather/

  ArrayOfRecordsCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Classifiers:
        - !Ref ClassifierName
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"}},"Grouping":{"TableGroupingPolicy":"CombineCompatibleSchemas"}}'
      DatabaseName: !Ref DatabaseName
      Name: !Sub ${StudyName}-array-of-records
      RecrawlPolicy:
        RecrawlBehavior: CRAWL_NEW_FOLDERS_ONLY
      Role: !Ref RoleArn
      SchemaChangePolicy:
        DeleteBehavior: LOG
        UpdateBehavior: LOG
      Targets:
        S3Targets:
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=motion/
          - Exclusions: []
            Path: !Sub s3://${BucketName}/${StudyName}/${JsonPrefix}/dataset=microphone_levels/

Outputs:

  StandardCrawlerName:
    Value: !Ref StandardCrawler
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-StandardCrawlerName'

  ArrayCrawlerName:
    Value: !Ref ArrayOfRecordsCrawler
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-ArrayCrawlerName'
