AWSTemplateFormatVersion: '2010-09-09'
Description: The set of Glue jobs created for each study

Parameters:

  SourceBucketName:
    Type: String
    Description: Name of S3 bucket where templates and scripts are stored

  BranchOrTagName:
    Type: String
    Description: >-
      Relevant branch or tag from where templates and scripts are sourced;
      this is used to build up the path to the correct object keys in the bucket
    Default: main

  JobRole:
    Type: String
    Description: The name or ARN of the IAM role that will run this job.

  S3OutputBucketName:
    Type: String
    Description: The S3 output bucket where temporary files will be written.

Resources:

  TaskResultParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export taskresult data in parquet format
        GlueTableName: taskresult
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  TaskDataParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export taskdata data in parquet format
        GlueTableName: taskdata
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  AnswersParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export answers data in parquet format
        GlueTableName: answers
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  InfoParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export info data in parquet format
        GlueTableName: info
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  MetadataParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export metadata data in parquet format
        GlueTableName: metadata
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  MicrophoneLevelsParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export microphone levels data in parquet format
        GlueTableName: microphone_levels
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  MotionParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export motion data in parquet format
        GlueTableName: motion
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  WeatherParquetJob:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Export weather data in parquet format
        GlueTableName: weather
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/json_s3_to_parquet.py

  S3ToJsonS3Job:
    Type:  AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${SourceBucketName}.s3.amazonaws.com/${BranchOrTagName}/templates/glue-job.yaml
      Parameters:
        JobDescription: Convert data to JSONS3 data
        JobRole: !Ref JobRole
        S3OutputBucketName: !Ref S3OutputBucketName
        S3ScriptLocation: !Sub s3://${SourceBucketName}/${BranchOrTagName}/glue/jobs/s3_to_json_s3.py

Outputs:

  AnswersParquetJobName:
    Value: !Ref AnswersParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-AnswersParquetJobName'

  InfoParquetJobName:
    Value: !Ref InfoParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-InfoParquetJobName'

  MetadataParquetJobName:
    Value: !Ref MetadataParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-MetadataParquetJobName'

  MicrophoneLevelsParquetJobName:
    Value: !Ref MicrophoneLevelsParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-MicrophoneLevelsParquetJobName'

  MotionParquetJobName:
    Value: !Ref MotionParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-MotionParquetJobName'

  TaskDataParquetJobName:
    Value: !Ref TaskDataParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-TaskDataParquetJobName'

  TaskResultParquetJobName:
    Value: !Ref TaskResultParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-TaskResultParquetJobName'

  WeatherParquetJobName:
    Value: !Ref WeatherParquetJob
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-WeatherParquetJobName'

  S3ToJsonS3JobName:
    Value: !Ref S3ToJsonS3Job
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-S3ToJsonS3JobName'
