AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Creates an SQS queue and corresponding dead-letter queue and
  subscribes that queue to an SNS topic

Parameters:

  MessageRetentionPeriod:
    Type: Number
    Default: 1209600
    Description: How long to retain messages in the primary queue.

  SubscribePrimaryToSNS:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Whether to subscribe the PrimaryQueue to an SNS topic

Conditions:
  SubscribeSNS: !Equals
    - !Ref SubscribePrimaryToSNS
    - 'true'

Resources:

  PrimaryQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      QueueName: !Sub '${AWS::StackName}-Queue'
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 120

  PrimaryQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Admin
          Effect: Allow
          Principal:
            AWS: !Sub '${AWS::AccountId}'
          Action:
          - SQS:*
          Resource: !GetAtt PrimaryQueue.Arn
      Queues:
      - !Ref PrimaryQueue

  PrimaryQueueSNSPolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: SubscribeSNS
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: SNSSend
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - SQS:SendMessage
          Resource: !GetAtt PrimaryQueue.Arn
          Condition:
            ArnLike:
              "aws:SourceArn": !Ref SnsTopic
      Queues:
      - !Ref PrimaryQueue

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MessageRetentionPeriod: 1209600
      QueueName: !Sub '${AWS::StackName}-DeadLetterQueue'
      ReceiveMessageWaitTimeSeconds: 10
      RedriveAllowPolicy:
        redrivePermission: 'allowAll'
      VisibilityTimeout: 30

  DeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Admin
          Effect: Allow
          Principal:
            AWS: !Sub '${AWS::AccountId}'
          Action:
          - SQS:*
          Resource: !GetAtt DeadLetterQueue.Arn
      Queues:
      - !Ref DeadLetterQueue

  SnsTopic:
    Condition: SubscribeSNS
    Type: AWS::SNS::Topic

  SnsSubscription:
    Condition: SubscribeSNS
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SnsTopic
      Endpoint: !GetAtt PrimaryQueue.Arn

Outputs:

  PrimaryQueueArn:
    Value: !GetAtt PrimaryQueue.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-PrimaryQueueArn'

  PrimaryQueueUrl:
    Value: !Ref PrimaryQueue
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-PrimaryQueueUrl'
