AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Creates an SQS queue and corresponding dead-letter queue and
  subscribes that queue to an SNS topic

Resources:

  PrimaryQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MessageRetentionPeriod: 86400
      QueueName: !Sub '${AWS::StackName}-Queue'
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 120

  PrimaryQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Admin
          Effect: Allow
          Principal:
            AWS: !Sub '${AWS::AccountId}'
          Action:
          - SQS:*
          Resource: !Ref PrimaryQueue
        - Sid: SNS
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - SQS:SendMessage
          Resource: !Ref PrimaryQueue
          Condition:
            ArnEquals:
              'aws:SourceArn': !Ref SnsTopic

      Queues:
      - !Ref PrimaryQueue

  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MessageRetentionPeriod: 1209600
      QueueName: !Sub '${AWS::StackName}-DeadLetterQueue'
      ReceiveMessageWaitTimeSeconds: 10
      RedriveAllowPolicy:
        redrivePermission: 'allowAll'
      VisibilityTimeout: 30

  DeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Admin
          Effect: Allow
          Principal:
            AWS: !Sub '${AWS::AccountId}'
          Action:
          - SQS:*
          Resource: !Ref DeadLetterQueue
      Queues:
      - !Ref DeadLetterQueue

  SnsTopic:
    Type: AWS::SNS::Topic

  SnsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SnsTopic
      Endpoint: !GetAtt PrimaryQueue.Arn
