AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >
  python3.8

  SAM Template for sns-to-glue

Parameters:

  Namespace:
    Type: String
    Description: Namespace of the stack so that it may be unique

  SQSQueueArn:
    Type: String
    Description: ARN of SQS queue to poll for messages

Resources:

  SqsToGlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: StartGlueWorkflow
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - glue:StartWorkflowRun
            - glue:PutWorkflowRunProperties
            Resource:
            - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:workflow/*

  SqsToGlueFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Role: !GetAtt SqsToGlueRole.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 20
            MaximumBatchingWindowInSeconds: 20
            Queue: !Ref SQSQueueArn
      Timeout: 600
      Environment:
        Variables:
          NAMESPACE: !Ref Namespace
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./sns_to_glue
      DockerTag: v0.1

  LambdaInvocationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SqsToGlueFunction.Arn
      Action: lambda:InvokeFunction
      SourceArn: !Ref SQSQueueArn
      Principal: sqs.amazonaws.com
